### ISSUE TITLE
No age in years w/ #s like 5-120 ??

### ISSUE THREAD

**Issue by paynito** [stephlocke/mockaRoo#1]
Don't want to mess with creating a new column changing your random date genator to an age.  Great tool!

**Comment by paynito** [comment]
oops,  can be done w/ the Number choice, closing.

**Comment by stephlocke** [comment]
Glad someone's using this :-) I'd be really interested to hear how you're using it and how it does/doesn't suit your needs so it can be improved

**Comment by paynito** [comment]
Hi steph, I'm working with census datasets of a million rows.  I was using your api to make similar data of just 100 lines to work with more quickly and get things set up nicely before running the larger set.
